version: "3.6"
networks:
  spring:
services:
  nginx:
    hostname: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - spring
  spring1: &app
    hostname: spring1
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spring
  spring2:
    << : *app
    hostname: spring2
  spring3:
    << : *app
    hostname: spring3
