version: "3.6"
networks:
  monitoring:
services:
  spring:
    hostname: spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monitoring
  prometheus:
    hostname: prometheus
    image: "prom/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=365d'
      - '--storage.tsdb.allow-overlapping-blocks'
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    networks:
      - monitoring
  grafana:
    hostname: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-polystat-panel"
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
    networks:
      - monitoring
