version: "3.6"
networks:
  keycloak_net:
services:
  pyspark:
    image: quay.io/keycloak/keycloak:21.0.1
    hostname: keycloak
    networks:
      - keycloak_net
    ports:
      - 18080:8080 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin 
